import { ArrowRight, BarChart3, CheckCircle2, ClipboardCheck, TimerReset } from "lucide-react";
import { ButtonLink } from "@/ui/components/button";
import { Progress } from "@/ui/components/progress";
import { Surface } from "@/ui/components/surface";
import { Eyebrow, PageTitle } from "@/ui/components/typography";
import { AssessmentRail } from "@/ui/patterns/assessment-rail";

const principles = [
  { icon: ClipboardCheck, title: "Chọn đúng trọng tâm", description: "Tìm đề theo chủ đề để dành thời gian cho phần kiến thức bạn thực sự cần luyện." },
  { icon: TimerReset, title: "Giữ nhịp làm bài", description: "Thời gian, tiến độ và trạng thái từng câu luôn hiện đúng lúc, không gây phân tâm." },
  { icon: BarChart3, title: "Đọc kết quả để tiến bộ", description: "Dùng dữ liệu sau mỗi phiên để quyết định bài luyện tiếp theo có chủ đích." },
];

export default function HomePage() {
  return <main><section className="assessment-grid overflow-hidden border-b border-line"><div className="mx-auto grid min-h-[590px] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.08fr_.92fr]"><div><Eyebrow>Luyện tập có chủ đích</Eyebrow><PageTitle className="mt-4 max-w-3xl text-5xl leading-[0.98] sm:text-7xl">Luyện đúng phần.<br/><span className="text-cobalt">Thi chắc tay.</span></PageTitle><p className="mt-6 max-w-xl text-lg leading-8 text-slate">Quizboard biến mỗi lượt làm bài thành một phiên đánh giá rõ ràng: biết mình đang ở đâu, cần làm gì tiếp theo và tiến bộ ra sao.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink size="lg" href="/tests">Khám phá kho đề <ArrowRight size={18} aria-hidden="true"/></ButtonLink><ButtonLink size="lg" intent="secondary" href="/register">Tạo tài khoản</ButtonLink></div></div><Surface className="relative overflow-hidden" padding="lg"><div className="absolute inset-y-0 left-0 w-1.5 bg-cobalt" aria-hidden="true"/><div className="flex items-center justify-between gap-4"><div><Eyebrow>Phiên làm bài</Eyebrow><h2 className="mt-2 font-display text-2xl font-bold tracking-[-0.035em]">Kiến trúc phần mềm</h2></div><span className="rounded-full bg-teal-soft px-3 py-1 font-mono text-xs text-teal">Đang luyện</span></div><div className="mt-7 grid grid-cols-3 gap-3 text-center"><div className="rounded-[var(--radius-sm)] bg-paper p-3"><p className="font-mono text-xl font-medium">24</p><p className="mt-1 text-xs text-slate">câu hỏi</p></div><div className="rounded-[var(--radius-sm)] bg-paper p-3"><p className="font-mono text-xl font-medium">30′</p><p className="mt-1 text-xs text-slate">thời gian</p></div><div className="rounded-[var(--radius-sm)] bg-paper p-3"><p className="font-mono text-xl font-medium text-teal">82%</p><p className="mt-1 text-xs text-slate">mục tiêu</p></div></div><Progress className="mt-7" label="Đã trả lời 14/24 câu" value={58}/><AssessmentRail className="mt-7" active={2}/><p className="mt-3 flex items-center gap-2 text-sm text-slate"><CheckCircle2 size={16} className="text-teal" aria-hidden="true"/>Đáp án được lưu trong suốt phiên làm bài.</p></Surface></div></section><section className="mx-auto max-w-7xl px-5 py-20"><Eyebrow>Một quy trình liền mạch</Eyebrow><h2 className="mt-3 max-w-2xl font-display text-3xl font-bold tracking-[-0.04em] sm:text-4xl">Từ chọn đề đến quyết định học gì tiếp theo.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{principles.map(({ icon: Icon, title, description }) => <Surface key={title} tone="flat"><span className="grid size-10 place-items-center rounded-[var(--radius-sm)] bg-cobalt-soft text-cobalt"><Icon size={19} aria-hidden="true"/></span><h3 className="mt-8 font-display text-xl font-bold tracking-[-0.025em]">{title}</h3><p className="mt-3 leading-7 text-slate">{description}</p></Surface>)}</div></section></main>;
}
